
import { Property, AppUser } from './types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Modern Lakeview Duplex',
    price: 25000,
    type: 'House',
    beds: 3,
    baths: 2,
    sqft: 1250,
    locationName: 'Dhanmondi, Dhaka',
    description: 'Beautiful modern duplex house with direct view of Dhanmondi Lake. Features 3 bedrooms, 2 bathrooms, modern kitchen and a spacious balcony perfect for evening tea.',
    imageColor: 'from-emerald-600 via-teal-600 to-cyan-700',
    x: 220,
    y: 580,
    amenities: ['Wi-Fi', 'Security', 'AC', 'Parking'],
    isApproved: true,
    host: {
      name: 'Sajjad Godrej',
      avatar: 'SG',
      phone: '01700000002',
      rating: 4.8
    }
  },
  {
    id: 'prop-2',
    title: 'Luxury Family Apartment',
    price: 35000,
    type: 'Apartment',
    beds: 4,
    baths: 3,
    sqft: 1850,
    locationName: 'Bashundhara R/A, Dhaka',
    description: 'Spacious and safe family apartment in Bashundhara Block-D. Includes 24/7 security, elevator access, underground parking, and community gym membership.',
    imageColor: 'from-blue-600 via-indigo-600 to-purple-700',
    x: 680,
    y: 380,
    amenities: ['Parking', 'Elevator', 'Security', 'Gym'],
    isApproved: true,
    host: {
      name: 'Rafi Islam',
      avatar: 'RI',
      phone: '01700000001',
      rating: 4.5
    }
  },
  {
    id: 'prop-3',
    title: 'Comfortable Room',
    price: 8500,
    type: 'Room',
    beds: 1,
    baths: 1,
    sqft: 250,
    locationName: 'Uttara, Dhaka',
    description: 'Cozy private room with ensuite bathroom. Ideal for students or single working professionals looking for a clean, budget-friendly workspace in sector 11, Uttara.',
    imageColor: 'from-amber-500 via-orange-600 to-red-700',
    x: 480,
    y: 160,
    amenities: ['Wi-Fi', 'AC', 'Security'],
    isApproved: true,
    host: {
      name: 'Md. Shakib',
      avatar: 'MS',
      phone: '01700000005',
      rating: 4.7
    }
  },
  {
    id: 'prop-4',
    title: 'Nice Family House',
    price: 22000,
    type: 'House',
    beds: 3,
    baths: 2,
    sqft: 1100,
    locationName: 'Mirpur, Dhaka',
    description: 'Spacious family apartment located in Mirpur-12, close to Metro Rail station. Features great natural airflow, front balcony garden, gas supply, and 24-hour sweet water access.',
    imageColor: 'from-indigo-600 via-purple-600 to-rose-700',
    x: 180,
    y: 320,
    amenities: ['Parking', 'Wi-Fi', 'Security'],
    isApproved: true,
    host: {
      name: 'Farhana Islam',
      avatar: 'FI',
      phone: '01700000006',
      rating: 4.6
    }
  },
  {
    id: 'prop-5',
    title: 'Premium Corporate Office',
    price: 65000,
    type: 'Office',
    beds: 0,
    baths: 2,
    sqft: 2100,
    locationName: 'Gulshan-2, Dhaka',
    description: 'State-of-the-art office unit located in the commercial heart of Gulshan. Includes conference rooms, server cabinet spaces, high-speed fiber internet, and receptionist lounge.',
    imageColor: 'from-blue-700 via-sky-800 to-indigo-900',
    x: 750,
    y: 620,
    amenities: ['Wi-Fi', 'AC', 'Parking', 'Security', 'Conference Room'],
    isApproved: true,
    host: {
      name: 'Rony Ahmed',
      avatar: 'RA',
      phone: '01700000007',
      rating: 4.95
    }
  },
  {
    id: 'prop-6',
    title: 'Cozy Shared Apartment',
    price: 12000,
    type: 'Room',
    beds: 2,
    baths: 1,
    sqft: 450,
    locationName: 'Banani, Dhaka',
    description: 'Beautifully furnished shared studio room in Banani block F. Direct walking distance to premium restaurants, cafes, and universities. Access to shared living room and full kitchen.',
    imageColor: 'from-fuchsia-600 via-pink-700 to-rose-900',
    x: 520,
    y: 740,
    amenities: ['Wi-Fi', 'AC', 'Security', 'Kitchen'],
    isApproved: false,
    host: {
      name: 'Elena Rostova',
      avatar: 'ER',
      phone: '01700000008',
      rating: 4.2
    }
  }
];

export const MOCK_USERS: AppUser[] = [
  { id: 'u1', name: 'Rafi Islam', email: 'customer@example.com', phone: '01700000001', role: 'customer', avatar: 'RI', password: 'password' },
  { id: 'u2', name: 'Sajjad Godrej', email: 'owner@example.com', phone: '01700000002', role: 'owner', avatar: 'SG', password: 'password' },
  { id: 'u3', name: 'Admin', email: 'admin', phone: '99388', role: 'company', avatar: 'AD', password: '99388' }
];

export const TRANSLATIONS: any = {
  EN: {
    appName: "Abashon",
    motto: "Easy Rentals, Better Living",
    portalSubtitle: "Premium Real Estate System: Customer Map, Landlord Ad Portal, & Corporate Upload Admin",
    customerPortal: "Customer Portal",
    clientOwner: "Client / Owner",
    companyWorkspace: "Company Workspace",
    hello: "Hello, Rafi Islam",
    searchPlaceholder: "Search area, rent or property...",
    categorySelect: "Category Select",
    dhakaDistricts: "Dhaka Districts",
    seeAll: "See All",
    matchedAds: "Dynamic Matched Ads",
    setSearchArea: "Set Search Area",
    discoverGems: "Discover Rental Gems with Radius-Based Search",
    liveGrid: "Live Abashon Grid",
    rentLimitLabel: "Max Rent (BDT ৳)",
    dhakaSector: "Dhaka Sector",
    minBeds: "Min Bedrooms Required",
    applyView: "Apply and View",
    any: "Any",
    noMatched: "No live properties match current criteria. Try adjusting the search radius or rent sliders.",
    postAd: "Post New Rental Advertisement",
    adTitle: "Advertisement Title",
    rentPrice: "Rent Price (Monthly BDT)",
    propertyType: "Property Type",
    selectRegion: "Select Dhaka Neighborhood",
    sqftSize: "Property Size (Sq Ft)",
    bedCount: "Bedrooms Count",
    bathCount: "Bathrooms Count",
    amenities: "Amenities Available",
    description: "Public Description",
    submitAd: "Publish Active Advertisement",
    details: "Detail View",
    lease: "/ Month Lease",
    amenitiesTitle: "Premium Amenities Included",
    hostInfo: "Listing Host Information",
    responseRate: "Response Rate:",
    responseTime: "Response Time:",
    inquireBtn: "Inquire About Leasing",
    savedListings: "Saved Property Bookmarks",
    noSaved: "You have not bookmarked any properties yet. Explore the live map and click the heart icon!",
    chatsTitle: "Your Message Inbox Threads",
    noChats: "No active conversations. Start a chat by clicking 'Inquire About Leasing' on any property details screen.",
    activeChat: "Live Inquiry Thread",
    typingPlaceholder: "Write your inquiry...",
    send: "Send",
    back: "Back",
    adminConsole: "Administrative Property Loader Console",
    bulkDescription: "Bulk inject new verified listings into the Abashon system using standard structured JSON formatting.",
    importSample: "Generate Sample JSON Dataset",
    importAction: "Execute Safe Bulk Import",
    activeProperties: "Active Properties Database Status",
    platformSettings: "Platform Governance & Operational Metrics",
    platformFee: "Global Platform Facilitation Fee (%)",
    registrationOpen: "Open Public Registration for Landlords",
    autoApprove: "Auto-Approve Landlord Submissions",
    systemLogs: "Abashon Real-Time Platform Event Engine Logs",
    systemActive: "SYSTEM SECURE ENGINE ONLINE",
    ownerDashboard: "Landlord Advertisement Dashboard",
    postAdSubtitle: "Launch real-time validated listings directly into Abashon's radius-based discovery map",
    yourActiveListings: "Your Live Property Ads on Abashon",
    pendingApproval: "PENDING COMPANY AUDIT",
    approvedLive: "LIVE & VERIFIED",
    featuredBadge: "FEATURED",
    dhakaCityMap: "Dhaka Metro Interactive Spatial Map",
    interactiveMapDesc: "Interactive spatial coordinates grid. Click anywhere to change your search radius focal point anchor.",
    mapRadiusLabel: "Search Radius (kms):",
    mapAnchorLabel: "Radius Center:",
    mapHoverLabel: "Selected Location:",
  },
  BN: {
    appName: "আবাসন",
    motto: "সহজ ভাড়া, উন্নত জীবন",
    portalSubtitle: "প্রিমিয়াম রিয়েল এস্টেট সিস্টেম: কাস্টমার ম্যাপ, ল্যান্ডলর্ড অ্যাড পোর্টাল এবং কর্পোরেট আপলোড অ্যাডমিন",
    customerPortal: "গ্রাহক পোর্টাল",
    clientOwner: "মালিক / বিজ্ঞাপন দাতা",
    companyWorkspace: "কোম্পানি ওয়ার্কস্পেস",
    hello: "হ্যালো, রাফি ইসলাম",
    searchPlaceholder: "এলাকা, ভাড়া বা ফ্ল্যাট খুঁজুন...",
    categorySelect: "ক্যাটাগরি নির্বাচন করুন",
    dhakaDistricts: "ঢাকার এলাকা সমূহ",
    seeAll: "সব দেখুন",
    matchedAds: "মিলে যাওয়া বিজ্ঞাপন সমূহ",
    setSearchArea: "অনুসন্ধানের এলাকা নির্ধারণ করুন",
    discoverGems: "ব্যাসার্ধ-ভিত্তিক অনুসন্ধানের মাধ্যমে সেরা ফ্ল্যাট খুঁজুন",
    liveGrid: "লাইভ আবাসন গ্রিড",
    rentLimitLabel: "সর্বোচ্চ ভাড়া (টাকা ৳)",
    dhakaSector: "ঢাকার সেক্টর",
    minBeds: "নূন্যতম বেডরুমের সংখ্যা",
    applyView: "প্রয়োগ করুন এবং দেখুন",
    any: "যেকোনো",
    noMatched: "বর্তমান ফিল্টারে কোনো বিজ্ঞাপন পাওয়া যায়নি। ব্যাসার্ধ বা ভাড়া পরিবর্তন করে আবার চেষ্টা করুন।",
    postAd: "নতুন ভাড়ার বিজ্ঞাপন পোস্ট করুন",
    adTitle: "বিজ্ঞাপনের শিরোনাম",
    rentPrice: "ভাড়ার পরিমাণ (মাসিক টাকা)",
    propertyType: "প্রপার্টির ধরন",
    selectRegion: "ঢাকার এলাকা নির্বাচন করুন",
    sqftSize: "আয়তন (বর্গফুট)",
    bedCount: "বেডরুমের সংখ্যা",
    bathCount: "বাথরুমের সংখ্যা",
    amenities: "বিদ্যমান সুবিধাসমূহ",
    description: "বিস্তারিত বিবরণ",
    submitAd: "বিজ্ঞাপনটি প্রকাশ করুন",
    details: "বিস্তারিত তথ্য",
    lease: "/ মাসিক লিজ",
    amenitiesTitle: "অন্তর্ভুক্ত সুযোগ-সুবিধাসমূহ",
    hostInfo: "হোস্ট সংক্রান্ত তথ্য",
    responseRate: "যোগাযোগের হার:",
    responseTime: "উত্তরের সময়:",
    inquireBtn: "ভাড়ার ব্যাপারে যোগাযোগ করুন",
    savedListings: "সংরক্ষিত বিজ্ঞাপন সমূহ",
    noSaved: "আপনি এখনও কোনো বিজ্ঞাপন বুকমার্ক করেননি। ম্যাপটি ঘুরে দেখুন এবং হার্ট আইকন ক্লিক করুন!",
    chatsTitle: "বার্তা ও যোগাযোগ সমূহ",
    noChats: "কোনো বার্তা নেই। যেকোনো প্রপার্টির ডিটেইলস স্ক্রিনে 'যোগাযোগ করুন' ক্লিক করে কথা শুরু করুন।",
    activeChat: "সরাসরি বার্তা বিনিময়",
    typingPlaceholder: "আপনার মেসেজ লিখুন...",
    send: "পাঠান",
    back: "ফিরে যান",
    adminConsole: "প্রশাসনিক প্রপার্টি লোডার কনসোল",
    bulkDescription: "আবাসন সিস্টেমে স্ট্যান্ডার্ড স্ট্রাকচার্ড JSON ফরমেট ব্যবহার করে ভেরিফাইড ফ্ল্যাটের বাল্ক এন্ট্রি করুন।",
    importSample: "নমুনা JSON ডেটা তৈরি করুন",
    importAction: "বাল্ক ইম্পোর্ট কার্যকর করুন",
    activeProperties: "সক্রিয় প্রপার্টি ডাটাবেস স্ট্যাটাস",
    platformSettings: "প্ল্যাটফর্ম পরিচালনা ও নিয়ামক সমূহ",
    platformFee: "গ্লোবাল প্ল্যাটফর্ম সুবিধা ফি (%)",
    registrationOpen: "বাড়ির মালিকদের উন্মুক্ত রেজিস্ট্রেশন",
    autoApprove: "বিজ্ঞাপন স্বয়ংক্রিয়ভাবে অনুমোদন করুন",
    systemLogs: "আবাসন রিয়েল-টাইম প্ল্যাটফর্ম ইভেন্ট ইঞ্জিন লগ",
    systemActive: "সিস্টেম সিকিউর ইঞ্জিন অনলাইন",
    ownerDashboard: "জমিনদার / বাড়িওয়ালার ড্যাশবোর্ড",
    postAdSubtitle: "আবাসনের ব্যাসার্ধ-ভিত্তিক অনুসন্ধানের ম্যাপে সরাসরি বিজ্ঞাপন প্রকাশ করুন",
    yourActiveListings: "আবাসনে আপনার সক্রিয় বিজ্ঞাপন সমূহ",
    pendingApproval: "অনুমোদনের অপেক্ষায়",
    approvedLive: "সরাসরি লাইভ ও ভেরিফাইড",
    featuredBadge: "ফিচার্ড বিজ্ঞাপন",
    dhakaCityMap: "ঢাকা মেট্রো ইন্টারেক্টিভ স্পেশাল ম্যাপ",
    interactiveMapDesc: "ইন্টারেক্টিভ স্থানাঙ্ক গ্রিড। ব্যাসার্ধের কেন্দ্রবিন্দু পরিবর্তন করতে ম্যাপের যেকোনো স্থানে ক্লিক করুন।",
    mapRadiusLabel: "অনুসন্ধান ব্যাসার্ধ (কিমি):",
    mapAnchorLabel: "ব্যাসার্ধ কেন্দ্র:",
    mapHoverLabel: "নির্বাচিত অবস্থান:",
  }
};
